### ISSUE TITLE
How do you show the "cheatsheet"?

### ISSUE THREAD

**Issue by dmitrym0** [mobily/awesome-keys#1]
Hi @mobily , wonderful package. I can't seem to figure out how to show the cheatsheet (all the key mappings). Are you using a separate spoon for this?

**Comment by mobily** [comment]
hey @dmitrym0 👋 the plugin only shows defined key bindings :) 

firstly, you need to create a new HyperBindings instance:

```lua
local hyper =
  keys:createHyperBindings(
  {
    hyperKey = "f20" -- use karabiner to remap any key to f20
  }
)
```
 
secondly, add custom key bindings by using `hyper:setGlobalBindings` (global, top row) or `hyper:setAppBindings` (app-specific, bottom row), you can actually find a few examples in README.md

once you did it, you can (de)activate the "cheatsheet" with F20 (or any other hyper key you set in the config)

**Comment by dmitrym0** [comment]
Ahh here it is:
```
2022-03-07 09:13:20: 09:13:20 ** Warning:   LuaSkin: invalid font specified: JetBrains Mono
```

I was missing a font, it's all good now, I see the hints.

**Comment by mobily** [comment]
great to hear that! 🎉 I thought if a font isn't installed, Hammerspoon will use the system font by default, but apparently, it doesn't do that

**Comment by dmitrym0** [comment]
@mobily I've got a couple of other questions if you don't mind!

1. is it possible to display the cheat sheet for the "global bindings"? Right now I only get the window when I activate the hyper mode.
2. Once in hyper mode, the only way to deactivate it is to hit the hyper key combo again. Is there a way to quit the hyper mode once the key is hit?

So far this is really great 👍

**Comment by mobily** [comment]
@dmitrym0 

1. do you mean the bindings that are defined in `keys:setGlobalBindings`? (and not in `hyper:keys:setGlobalBindings`) if so, then, unfortunately, it's impossible at the moment, but I'm open to suggestions!
2. yes, please use the `hyperExitKey` param, see: https://github.com/mobily/awesome-keys#spoonawesomekeyscreatehyperbindingsconfig

**Comment by dmitrym0** [comment]
For #1 there is https://www.hammerspoon.org/Spoons/HSKeybindings.html, It's working fairly well for me, of course not as attractive as yours!

For #2, then awesomekeys uses the modal approach, kind of like vim?
